// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLhrDh1_EGWB3VTDOGWbCg_SnLVU7pWH0',
    appId: '1:978486244043:web:a4ff166a0a0a40e080214e',
    messagingSenderId: '978486244043',
    projectId: 'dotix-1d518',
    authDomain: 'dotix-1d518.firebaseapp.com',
    storageBucket: 'dotix-1d518.firebasestorage.app',
    measurementId: 'G-E7C2XHKW02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd-Z9zR25ddXZxihbwU38MEAvxlldECWw',
    appId: '1:978486244043:android:c66b0716d3a622ae80214e',
    messagingSenderId: '978486244043',
    projectId: 'dotix-1d518',
    storageBucket: 'dotix-1d518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpHcuN3kQRvHGQstcp2PSutSHGiAmy_U',
    appId: '1:978486244043:ios:851c12eb8ca036bc80214e',
    messagingSenderId: '978486244043',
    projectId: 'dotix-1d518',
    storageBucket: 'dotix-1d518.firebasestorage.app',
    iosClientId: '978486244043-bb314q8b0q9t3g6lpqe6rvbmrs2j6d7i.apps.googleusercontent.com',
    iosBundleId: 'com.app.rewarddaddy.myreward.dotix5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpHcuN3kQRvHGQstcp2PSutSHGiAmy_U',
    appId: '1:978486244043:ios:851c12eb8ca036bc80214e',
    messagingSenderId: '978486244043',
    projectId: 'dotix-1d518',
    storageBucket: 'dotix-1d518.firebasestorage.app',
    iosClientId: '978486244043-bb314q8b0q9t3g6lpqe6rvbmrs2j6d7i.apps.googleusercontent.com',
    iosBundleId: 'com.app.rewarddaddy.myreward.dotix5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLhrDh1_EGWB3VTDOGWbCg_SnLVU7pWH0',
    appId: '1:978486244043:web:a9ccb7b16cd7809280214e',
    messagingSenderId: '978486244043',
    projectId: 'dotix-1d518',
    authDomain: 'dotix-1d518.firebaseapp.com',
    storageBucket: 'dotix-1d518.firebasestorage.app',
    measurementId: 'G-VYL4CYHSFW',
  );
}
